export const RIGHT_PANEL_STYLES = {
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    boxSizing: "border-box",
    padding: "16px",
    backgroundColor: "#f8fafc",
    color: "#111827",
    border: "1px solid #cbd5e1",
    boxShadow: "0 4px 14px rgba(15, 23, 42, 0.12)",
    fontSize: "13px",
    lineHeight: "1.5",
  },
  heading: {
    margin: "0",
    color: "#0f172a",
    fontSize: "16px",
    fontWeight: "600",
  },
  description: {
    margin: "0",
    color: "#475569",
  },
  text: {
    color: "#334155",
  },
  formContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  status: {
    margin: "0",
    color: "#475569",
    overflowWrap: "break-word",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    color: "#334155",
    fontWeight: "500",
  },
  input: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "36px",
    padding: "8px 10px",
    color: "#111827",
    backgroundColor: "#ffffff",
    border: "1px solid #b8c1cc",
    borderRadius: "4px",
    font: "inherit",
  },
  expression: {
    minHeight: "96px",
    resize: "vertical",
  },
  methodSelect: {
    boxSizing: "border-box",
    width: "100%",
    minHeight: "36px",
    padding: "8px 10px",
    color: "#111827",
    backgroundColor: "#ffffff",
    border: "1px solid #b8c1cc",
    borderRadius: "4px",
    font: "inherit",
  },
  range: {
    width: "100%",
    accentColor: "#1d4ed8",
  },
  checkbox: {
    accentColor: "#1d4ed8",
  },
  radio: {
    accentColor: "#1d4ed8",
  },
  output: {
    color: "#0f172a",
    fontWeight: "600",
  },
  selectOption: {
    color: "#000000",
    backgroundColor: "#ffffff",
  },
  button: {
    minHeight: "36px",
    padding: "8px 12px",
    color: "#ffffff",
    backgroundColor: "#1d4ed8",
    border: "1px solid #1d4ed8",
    borderRadius: "4px",
    cursor: "pointer",
    font: "inherit",
    fontWeight: "600",
  },
  operationButton: {
    minHeight: "32px",
    padding: "6px 10px",
    color: "#ffffff",
    backgroundColor: "#2563eb",
    border: "1px solid #1d4ed8",
    borderRadius: "4px",
    cursor: "pointer",
    font: "inherit",
  },
  downloadButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "36px",
    padding: "8px 12px",
    color: "#ffffff",
    backgroundColor: "#0f766e",
    border: "1px solid #0f766e",
    borderRadius: "4px",
    cursor: "pointer",
    font: "inherit",
    fontWeight: "600",
    textDecoration: "none",
  },
  rasterList: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  rasterRow: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    padding: "10px",
    backgroundColor: "#ffffff",
    border: "1px solid #cbd5e1",
    borderRadius: "4px",
  },
  rasterControls: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  rasterBands: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  operations: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    padding: "8px",
    backgroundColor: "#e2e8f0",
    border: "1px solid #cbd5e1",
    borderRadius: "4px",
  },
  operationRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px",
  },
  countGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  mceRows: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  mceRow: {
    display: "grid",
    gap: "6px",
    padding: "10px",
    backgroundColor: "#ffffff",
    border: "1px solid #cbd5e1",
    borderRadius: "4px",
  },
  mceWeightInput: {
    boxSizing: "border-box",
    minHeight: "36px",
    padding: "8px 10px",
    color: "#111827",
    backgroundColor: "#ffffff",
    border: "1px solid #b8c1cc",
    borderRadius: "4px",
    font: "inherit",
  },
  ahpLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#334155",
    fontWeight: "500",
  },
  ahpContainer: {
    flexDirection: "column",
    gap: "8px",
    overflowX: "auto",
  },
  ahpInput: {
    boxSizing: "border-box",
    width: "72px",
    minHeight: "32px",
    padding: "6px",
    color: "#111827",
    backgroundColor: "#ffffff",
    border: "1px solid #b8c1cc",
    borderRadius: "4px",
    font: "inherit",
  },
  ahpButton: {
    alignSelf: "flex-start",
  },
  table: {
    borderCollapse: "collapse",
    width: "100%",
  },
  tableRow: {
    borderBottom: "1px solid #e2e8f0",
  },
  tableHeader: {
    padding: "6px",
    color: "#334155",
    fontWeight: "600",
    textAlign: "left",
  },
  tableCell: {
    padding: "6px",
    color: "#334155",
  },
  fieldset: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    margin: "0",
    padding: "10px",
    border: "1px solid #cbd5e1",
    borderRadius: "4px",
  },
  legend: {
    padding: "0 4px",
    color: "#334155",
    fontWeight: "600",
  },
  radioLabel: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    color: "#334155",
  },
  averagingGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  hidden: {
    display: "none",
  },
  visibleFlex: {
    display: "flex",
  },
} as const;

export type RightPanelStyleName = keyof typeof RIGHT_PANEL_STYLES;

export function applyRightPanelStyle(
  element: HTMLElement,
  styleName: RightPanelStyleName,
): void {
  const styles = RIGHT_PANEL_STYLES[styleName];
  element.classList.add(`right-panel-${styleName}`);
  Object.assign(element.style, styles);
}
